#!/bin/bash

kill_router() {
  echo "killing router..."
  sv down atlantis-router
  rm /etc/service/atlantis-router
  i=0
  while [ "$(pidof router)" ] && [ $i -lt 5 ]; do
    echo "waiting for router to die..."
    sleep 1
    (( i++ ))
  done
  if [ "$(pidof router)" ]; then
    echo "router is proving resilient. bringing out the big guns..."
    kill -9 $(pidof router)
  fi
  echo "router killed."
}

if [ -L '/etc/service/atlantis-router' ]; then
  kill_router
fi
